name: this is aravind 1st action

on: push

jobs:
    checkout-job:
        runs-on: ubuntu-24.04
        steps:
        - name: checkingoutrepo
          uses: actions/checkout@v4
        
        - name: install cowsay
          run: |
            echo "hello world"
            sudo apt-get install cowsay
        
        - name: run-cowsay
          run: cowsay -f dragon "love you gundu"



